spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecolearn
    username: postgres
    password: decho1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
